# Generated by Django 2.2.13 on 2020-10-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='square_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='img/square_author_images/'),
        ),
    ]
